version: 2
updates:
  - package-ecosystem: "npm"
    directories: ["/", "/docs"]
    schedule:
      interval: "monthly"
    versioning-strategy: "increase"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: fix(deps)
      prefix-development: chore(dev-deps)
    groups:
      all-minor-and-patch-updates:
        update-types:
          - "minor"
          - "patch"
        applies-to: "version-updates"
        patterns:
          - "*"
      major-updates:
        update-types:
          - "major"
        applies-to: "version-updates"
        patterns:
          - "*"
