name: Building the Project
run-name: Building project in ${{ github.head_ref || github.ref_name || github.base_ref }}

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

# Scanning only the last commit in the branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Try building
        run: |
          npm install
          npm run build
